// GENERATED by scripts/terrain/build_label_fonts.py — do not edit.
// Code points covered by the self-hosted label fonts; anything else is substituted
// or dropped client-side so troika never asks its unicode-font-resolver CDN.
export const ITALIC_CHARS = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\u00c0\u00c1\u00c2\u00c3\u00c4\u00c7\u00c9\u00ca\u00cb\u00cd\u00ce\u00cf\u00d6\u00d8\u00dc\u00e0\u00e1\u00e2\u00e3\u00e4\u00e7\u00e9\u00ea\u00eb\u00ed\u00ee\u00ef\u00f6\u00f8\u00fc\u014c\u014d\u2018\u2019"
export const TITLING_CHARS = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\u00c0\u00c1\u00c2\u00c3\u00c4\u00c7\u00c9\u00ca\u00cb\u00cd\u00ce\u00cf\u00d6\u00d8\u00dc\u00e0\u00e1\u00e2\u00e3\u00e4\u00e7\u00e9\u00ea\u00eb\u00ed\u00ee\u00ef\u00f6\u00f8\u00fc\u014c\u014d\u2018\u2019"
export const FONT_SUBSTITUTES: ReadonlyArray<readonly [number, number]> = [[0x02bb, 0x2018], [0x02bc, 0x2019]]
/** OS/2 sCapHeight / unitsPerEm (both cuts) */
export const CAP_HEIGHT_EM = 0.699
